mysite/mysite/urls.py
from django.conf.urls import url, include, patterns
from django.contrib import admin
admin.autodiscover()
from app.views import math, welcome, set_cookie, get_cookie, login, index, logout, register
from restaurants.views import menu, meta, list_restaurants, comment

urlpatterns = [
    #url(r'^admin/', include(admin.site.urls)),
    url(r'^admin/', admin.site.urls),
    #url(r'^here/', here),
    #url(r'^(\d{1,2})/math/(\d{1,2})/', math),
    url(r'^menu/(\d{1,5})/', menu),
    url(r'^meta/', meta),
    url(r'^welcome/', welcome),
    #restaurant
    url(r'^restaurants_list/', list_restaurants),
    url(r'^comment/(\d{1,5})/', comment),
    url(r'^set_c/', set_cookie),
    url(r'^get_c/', get_cookie),
    url(r'^index/', index),
    url(r'^login/', login),
    url(r'^logout/', logout),
    url(r'^accounts/register/', register),


]

mysite/restaurants/models.py
from django.db import models

# Create your models here.
class Restaurant(models.Model):
    name = models.CharField(max_length=20)
    phone_number = models.CharField(max_length=15)
    address = models.CharField(max_length=50, blank=True)
    def __str__(self):
        return self.name
    '''def __unicode__(self):  # Python 3: def __str__(self):
        return str(self.name)  3.5python 不適用
'''

class Food(models.Model):
    name = models.CharField(max_length=20)
    price = models.DecimalField(max_digits=3,decimal_places=0)
    comment = models.CharField(max_length=50, blank=True)
    is_spicy = models.BooleanField(default=False)
    restaurant = models.ForeignKey(Restaurant)
    def __str__(self):
        return self.name

class Meta:
    ordering = ['price']

class Comment(models.Model):
    content = models.CharField(max_length=255)
    visitor = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    date_time = models.DateTimeField()
    restaurant = models.ForeignKey(Restaurant)
    def __str__(self):
        return self.content
    class Meta:
        ordering = ['date_time']
        permissions = (
            ("can_comment", "Can_comment"),

        )
#from restaurants.models import Restaurant, Food
#創物件方法1
#r1 = Restaurant(name='雪碧餐廳', phone_number='02-6666666', address='天龍國天龍區天龍路100號')
#r1.save()
#創物件方法2
#r2 = Restaurant.objects.create(name='金魚餐廳', phone_number='02-6666666', address='天龍國天龍區天龍路100號')
#restaurants = Restaurant.objects.all()
#restaurants
#r2 = restaurants[1]
#r = Restaurant.objects.get(name='雪碧餐廳')
#f1 = Food(name='牛排', price=120, comment='本店招牌', is_spicy="False",restaurant = r)
#f2 = Food(name='炒馬鈴薯', price=60, comment='好吃小點', is_spicy="False",restaurant = r)

mysite/restaurants/forms.py
from django import forms



class CommentForm(forms.Form):

    """Comment Form class clear"""

    visitor = forms.CharField(max_length=20)
    email = forms.EmailField(max_length=20, required=False,label='E-mail')
    content = forms.CharField(max_length=200, widget=forms.Textarea())

    def clean_content(self):
        """check content if len > 5
        :returns: cleaned content
        """
        content = self.cleaned_data.get('content', '')
        if len(content) < 5:
            raise forms.ValidationError('字數不足')
        return content

mysite/app/views.py
# -*- conding:utf-8 -*-
from django.http import HttpResponse, HttpResponseRedirect
from django import template
from django.shortcuts import render_to_response
from django.shortcuts import render
from django.template import RequestContext
from django.contrib import auth
from django.contrib.auth.forms import UserCreationForm


def here(request):
    return HttpResponse('中文!')
def math(request, a, b):
    a = int(a)
    b = int(b)
    s = a + b
    d = a - b
    p = a * b
    q = a / b
    return  render_to_response('math.html',{'s':s, 'd':d, 'p':p, 'q':q},
    )
def welcome(request):
    if 'user_name' in request.GET and request.GET['user_name'] != '':
        return HttpResponse('Welcome!~'+request.GET['user_name'])
    else:
        return render_to_response('welcome.html', locals())

def set_cookie(request):
    response = HttpResponse('Set your lucky_number as 8')
    response.set_cookie('lucky_number', 8)
    return response

def get_cookie(request):
    if 'lucky_number' in request.COOKIES:
        return HttpResponse('Your lucky_number is {0}'.format(request.COOKIES['lucky_number']))
    else:
        return HttpResponse('NO cookies.')
def login(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect('/index/')
    username = request.POST.get('username', '')
    password = request.POST.get('password', '')

    user = auth.authenticate(username=username, password=password)
    if user is not None and user.is_active:
        auth.login(request, user)
        return HttpResponseRedirect('/index/')
    else:
        return render_to_response('login.html',RequestContext(request, locals()))



def index(request):
    """index page
    :request: client request
    :returns: index webpage
    """
    return render_to_response('index.html', RequestContext(request, locals()))

def logout(request):
    auth.logout(request)
    return HttpResponseRedirect('/index/')
def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            return HttpResponseRedirect('/login/')
    else:
        form =UserCreationForm()
    return render_to_response('register.html', RequestContext(request, locals()))

mysite/restaurants/views.py
#-*- coding: utf-8 -*-
from django.shortcuts import render
from django.shortcuts import render_to_response
from restaurants.models import Restaurant, Food,Comment
from django.http import HttpResponseRedirect, HttpResponse
from django.utils import timezone
from django.template import RequestContext
from restaurants.forms import CommentForm
from django.contrib.auth.decorators import login_required
# Create your views here.
def menu(request,id):
    if id:
    #path = request.path
        restaurant = Restaurant.objects.get(id=id)
        return render_to_response('menu.html',locals())
    else:
        return HttpResponseRedirect("/restaurants_list")
def meta(request):
    values = request.META.items()

    sorted(values)
    html = []
    for k, v in values:
        html.append('<tr><td>{0}</td><td>{1}</td></tr>'.format(k, v))
        return HttpResponse('<table>{0}</table>'.format('\n'.join(html)))

#@login_required
def list_restaurants(request):
    if not request.user.is_authenticated():
        return HttpResponseRedirect('/index/')
    restaurants = Restaurant.objects.all()
    return render_to_response('restaurants_list.html',RequestContext(request,locals()))


def comment(request, restaurant_id):

    if restaurant_id:
        r = Restaurant.objects.get(id=restaurant_id)
    else:
        return HttpResponseRedirect("/restaurants_list/")

    if request.POST:
        f = CommentForm(request.POST)
        if f.is_valid():
            visitor = f.cleaned_data['visitor']
            content = f.cleaned_data['content']
            email = f.cleaned_data['email']
            date_time = timezone.localtime(timezone.now())
            c = Comment.objects.create(
                visitor=visitor, email=email,
                content=content,
                date_time=date_time,
                restaurant=r
                )
            f = CommentForm(initial={'content':'我沒意見'})
    else:
        f = CommentForm(initial={'content':'我沒意見'})
    return render_to_response('comments.html', RequestContext(request, locals()))

mysite/app/templates/index.html
<!doctype html>
<html>
    <head>
        <title> Restaurant King </title>
        <meta charset='utf-8'>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css">
        <style>
        th { text-align: center; }
        div.center_padding {
            text-align: center;
            padding: 128px 15px;
        }
        </style>
    </head>
    <body>

        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">MySite</a>
                </div>
                <!--div id="navbar" class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="#">Home</a></li>
                        <li><a href="#about">About</a></li>
                        <li><a href="#contact">Contact</a></li>
                    </ul>
                </div--><!--/.nav-collapse -->
            </div>
        </nav>

        <div class="container">
            <div class="center_padding">
                <h2>歡迎來到餐廳王</h2>
                {% if request.user.is_authenticated %}
                <p>{{request.user}} 您已經登入囉
                  <a href="/logout/">登出</a>
                </p>
                <a href="/restaurants_list/">餐廳列表</a>
                {% else %}
                <p>您尚未登入喔~<a href="/login/">登入</a></p>
                {% endif %}
                <p> 若您還沒有帳號，請<a href="/accounts/register/">註冊</a></p>
            </div>
        </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
    </body>
</html>

mysite/app/templates/login.html
<!doctype html>
<html>
    <head>
        <title> Login </title>
        <meta charset='utf-8'>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css">
        <style>
        th { text-align: center; }
        div.center_padding {
            text-align: center;
            padding: 128px 15px;
        }
        </style>
    </head>
    <body>

        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">MySite</a>
                </div>
                <!--div id="navbar" class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="#">Home</a></li>
                        <li><a href="#about">About</a></li>
                        <li><a href="#contact">Contact</a></li>
                    </ul>
                </div--><!--/.nav-collapse -->
            </div>
        </nav>

        <div class="container">
            <div class="center_padding">
                <form action="" method="post" class="form-default" style="width:50%;margin:auto">{% csrf_token %}
                    <div class="form-group">
                    <label for="username">用戶名稱:</label>
                    <input type="text" name="username" value="{{username}}" id="username" class="form-control">
                    </div>
                    <div class="form-group">
                    <label for="password">用戶密碼:</label>
                    <input type="password" name="password" value="" id="password" class="form-control">
                    </div>
                    <input type="submit" value="登入" class="btn btn-default">
                </form>
            </div>
        </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
    </body>
</html>

mysite/app/templates/math.html
<html>
      sum={{s}}<br>
      dif={{d}}<br>
      pro={{p}}<br>
      quo={{q}}
      <h3>12315656</h3>
</html>

mysite/app/templates/menu.html
<!doctype html>
<html>
    <head>
        <title> Menu </title>
        <meat charset = 'utf-8'>
      </head>
      <body>
        <p>本餐廳共有{{foods|length}}道菜</p>

        {% for food in foods %}
        <h3>第{{ forloop.counter}}道食物</h3>
        <ul>
          <li>食物的名子是:{{ food.name }}</li>
          <li>食物的價格是:{{ food.price }}</li>
          <li>食物的說明是:{{ food.comment }}</li>
          <li>食物的會辣:{{ food.is_spicy }}</li>
        </ul>
        {% empty %}
        <p>本餐廳啥都沒賣</p>
        {% endfor %}
      </body>
</html>

mysite/app/templates/register.html
<!doctype html>
<html>
    <head>
        <title> Restaurants </title>
        <meat charset = 'utf-8'>
          <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
          <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css">

          <style>
          th { text-align: center; }
          div.menus {
            text-align: center;
            padding: 40px 15px;
          }





          </style>
      </head>
      <body>
        <!--
css版型設定
-->
          <nav class="navbar navbar-inverse navbar-fixed-top"
          role="navigation">
          <div class="container">
            <div class="navbar-header">
              <button type="button"
              class="navbar-toggle collapsed"
              data-toggle="collapse" data-target="#navbar"
              aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#">Sprite&Aiko kitchen</a>
            </div>
          </div>
        </nav>



        <!--
    資料讀取主體
    <td> <input type ="radio" name="id" value="{{r.id}}"> </td>
        -->
         <p>　</p>
        <p>　</p>
          <p>　</p>
<div class="container" >



        <h1>註冊新帳號</h1>
<form action="" method="post"> {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="註冊">



       <!--
      <input type="submit" value="觀看menu"> 選單式menu輸出鈕
       -->

     </form>


    </div>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
      </body>
</html>

mysite/app/templates/welcome.html
<!doctype html>
<html>
    <head>
        <title> Welcome </title>
        <meta charset='utf-8'>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css">
        <style>
        th { text-align: center; }
        div.center_padding {
            text-align: center;
            padding: 128px 15px;
        }
        </style>
    </head>
    <body>

        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">MySite</a>
                </div>
            </div>
        </nav>

        <div class="container">
            <div class="center_padding">
                <form action="" method="get" class="form-inline">
                    <label for="user_name">您的名字</label>
                    <input id="user_name" type="text" name="user_name" class="form-control" placeholder="例如：台灣人">
                    <input type="submit" value="進入網站" class="btn btn-default">
            </div>
        </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
    </body>
</html>

mysite/restaurants/templates/comments.html
<!doctype html>
<html>
    <head>
        <title> Comments </title>
        <meat charset = 'utf-8'>
          <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
          <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css">

          <style>
          th { text-align: center; }
          div.menus {
            text-align: center;
            padding: 40px 15px;
          }





          </style>
      </head>
      <body>
        <!--
css版型設定
-->
          <nav class="navbar navbar-inverse navbar-fixed-top"
          role="navigation">
          <div class="container">
            <div class="navbar-header">
              <button type="button"
              class="navbar-toggle collapsed"
              data-toggle="collapse" data-target="#navbar"
              aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="../../restaurants_list/">Sprite&Aiko kitchen"</a>
            </div>
          </div>
        </nav>



        <!--
    資料讀取主體
        -->
<div class="container">
  <div class="menus">
    <p>
      <!--
        #顯示路徑位置

      <p>您現在的位置在{{ path }}</p>
-->

        <h2>{{ r.name }}的評價</h2>
       {% if r.comment_set.all %}
       <p>目前共有{{ r.comment_set.all|length }}條評價</p>
       <table class="table">
           <tr>
               <th>留言者</th>
               <th>時間</th>
               <th>評價</th>
           </tr>
           {% for c in r.comment_set.all %}
           <tr>
               <td> {{ c.visitor }} </td>
               <td> {{ c.date_time | date:"D F j, Y"}} </td>
               <td> {{ c.content }} </td>

           </tr>
           {% endfor %}
       </table>
    </p>
       {% else %}
       <p>無評價</p>
       {% endif %}

       <br></br>


        {% if f.errors %}
              <p style="color:red;">請依提示修復表單</p>
        {% endif %}

       <form action="" method="post" > {% csrf_token %}
         <table align="center">
           <tr>
             <th><label for="id_vistor">留言者:</label></th>
             <td>{{ f.visitor}}</td>
             <td style="color:red;">{{ f.visitor.errors}}</td>
           </tr>
           <tr>
             <th><label for="id_email">電子信箱:</label></th>
             <td>{{ f.email}}</td>
             <td style="color:red;">{{ f.email.errors}}</td>
           </tr>
           <tr>
            <th> <label for="id_content">評論:</label></th>
             <td>{{ f.content}}</td>
             <td style="color:red;">{{ f.content.errors}}</td>
           </tr>
         </table>
         <input type="submit" value="給予評價">
       </form>
    </div>
  </div>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
      </body>
</html>

mysite/restaurants/templates/menu.html
<!doctype html>
<html>
    <head>
        <title> Menu </title>
        <meat charset = 'utf-8'>
          <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
          <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css">

          <style>
          th { text-align: center; }
          div.menus {
            text-align: center;
            padding: 40px 15px;
          }





          </style>
      </head>
      <body>
        <!--
css版型設定
-->
          <nav class="navbar navbar-inverse navbar-fixed-top"
          role="navigation">
          <div class="container">
            <div class="navbar-header">
              <button type="button"
              class="navbar-toggle collapsed"
              data-toggle="collapse" data-target="#navbar"
              aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="../../restaurants_list/">Sprite&Aiko kitchen</a>
            </div>
          </div>
        </nav>



        <!--
    資料讀取主體
        -->
<div class="container">
  <div class="menus">
    <p>
      <!--
        #顯示路徑位置

      <p>您現在的位置在{{ path }}</p>
-->

        <h2>{{ restaurant.name }}的Menu</h2>
       {% if restaurant.food_set.all %}
       <p>本餐廳共有{{ restaurant.food_set.all|length }}道菜</p>
       <table class="table">
           <tr>
               <th>菜名</th>
               <th>價格</th>
               <th>註解</th>
               <th>辣不辣</th>

           </tr>
           {% for food in restaurant.food_set.all %}
           <tr>
               <td> {{ food.name }} </td>
               <td> {{ food.price }} </td>
               <td> {{ food.comment }} </td>
               <td>{% if food.is_spicy %} 不辣 {% else %}
                                           辣 {% endif %} </td>
           </tr>
           {% endfor %}
       </table>
    </p>
       {% else %}
       <p>本餐廳啥都沒賣</p>
       {% endif %}

    </div>
  </div>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
      </body>
</html>

mysite/restaurants/templates/restaurants_list.html
<!doctype html>
<html>
    <head>
        <title> Restaurants </title>
        <meat charset = 'utf-8'>
          <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
          <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css">

          <style>
          th { text-align: center; }
          div.menus {
            text-align: center;
            padding: 40px 15px;
          }





          </style>
      </head>
      <body>
        <!--
css版型設定
-->
          <nav class="navbar navbar-inverse navbar-fixed-top"
          role="navigation">
          <div class="container">
            <div class="navbar-header">
              <button type="button"
              class="navbar-toggle collapsed"
              data-toggle="collapse" data-target="#navbar"
              aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#">Sprite&Aiko kitchen</a>
            </div>
          </div>
        </nav>



        <!--
    資料讀取主體
    <td> <input type ="radio" name="id" value="{{r.id}}"> </td>
        -->
<div class="container">
  <div class="menus">
    <p>


        <h2>餐廳列表</h2>
<form action="/menu/" method="get">
       <table class="table">
           <tr>
              <th>選取</th>
               <th>店名</th>
               <th>電話</th>
               <th>地址</th>
               <th>評價</th>


           </tr>
           {% for r in restaurants %}
           <tr>
               <td> <a href="/menu/{{r.id}}/">menu</a> </td>
               <td> {{ r.name }} </td>
               <td> {{ r.phone_number }} </td>
               <td> {{ r.address }} </td>
               <td> <a href="/comment/{{r.id}}">評論</a></td>
           </tr>
           {% endfor %}
       </table>

       <!--
      <input type="submit" value="觀看menu"> 選單式menu輸出鈕
       -->

     </form>
    </p>

    </div>
  </div>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
      </body>
</html>